# Generated by Django 4.1.1 on 2022-09-18 11:28

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=versatileimagefield.fields.VersatileImageField(upload_to=''),
        ),
    ]
