# Generated by Django 4.1.1 on 2022-09-24 04:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=55, verbose_name='Product Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='product.productcategory'),
        ),
    ]
