# Generated by Django 4.1.1 on 2022-09-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('cart', '0003_cartitem_product_cartitem_quantity_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
